Fix Faraday required minimum version
This change increases the Faraday required minimum version from `0.9` to `0.16.2`.

When running the tests with Faraday 0.15, we get the following error:

```
TypeError: superclass mismatch for class RequestOptions
```

This change also adds a `FARADAY_VERSION` environment variable and a Faraday matrix to the CI configuration.
By this addition, you can run the tests with any Faraday version like this:

```shell
FARADAY_VERSION='~> 0.16.0' bundle install && bundle exec rspec
```